- name: add ubuntu1 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.107 ubuntu1"
    state: present

- name: add ubuntu2 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.109 ubuntu2"
    state: present	

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: 'add users to docker group'
  user:
    name: 'ubuntu'
    groups: 'docker'
    append: 'yes'

- name: restart docker
  systemd:
    state: started
    name: docker