- name: add ubuntu1 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.106 ubuntu1"
    state: present

- name: add ubuntu2 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.107 ubuntu2"
    state: present

- name: debian | ensure the apt repository key is present
  apt_key:
    id="{{ oracle_java_apt_repository_key }}"
    keyserver=keyserver.ubuntu.com
    state=present
  when: oracle_java_apt_repository_key is defined
  become: yes

- name: debian | ensure the apt repository is present
  apt_repository:
    repo="{{ oracle_java_apt_repository }}"
    update_cache=yes
    state=present
  become: yes

- name: debian | set license as accepted
  debconf:
    name="{{ oracle_java_deb_package }}"
    question="{{ oracle_java_license_version }}"
    value='true'
    vtype='select'
  become: yes

- name: debian | ensure Java is installed
  apt:
    name="{{ oracle_java_deb_package }}"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  register: oracle_java_task_apt_install
  become: yes

- name: debian | set Java version as default
  apt:
    name="{{ oracle_java_debconf_package_default }}"
    state=present
  register: oracle_java_task_set_default
  become: yes

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: 'add users to docker group'
  user:
    name: 'ubuntu'
    groups: 'docker'
    append: 'yes'

- name: restart docker
  systemd:
    state: started
    name: docker