- name: add ubuntu1 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.106 ubuntu1"
    state: present

- name: add ubuntu2 hosts
  lineinfile:
    dest: /etc/hosts
    line: "192.168.1.107 ubuntu2"
    state: present

- name: download JRE
  apt: 
    name: openjdk-8-jdk 
    state: present
    update_cache: yes

- name: "Check gradle version is present"	
  stat:	
    path: "{{ gradle_link }}"	
  register: gradle_present	

- name: "Check gradle version is present"	
  shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"	
  changed_when: false	
  register: gradle_version_check	
  when: gradle_present.stat.exists	

- block:	

  - name: "Install unzip"	
    package:	
      name: unzip	
      state: latest	

  - name: "Download"	
    get_url:	
      url: "{{ gradle_download_url }}"	
      dest: "{{ gradle_download }}"	
      checksum: "{{ gradle_checksum }}"	

  - name: "Extract Gradle {{ gradle_version }}"	
    unarchive:	
      src: "{{ gradle_download }}"	
      dest: "{{ gradle_base_dir }}"	
      remote_src: True	

  - name: "Add gradle symlink to path"	
    file:	
      src: "{{ gradle_base_dir }}/{{ gradle_extract_dir }}/bin/gradle"	
      dest: "{{ gradle_link }}"	
      owner: root	
      group: root	
      state: link	

  - name: "Validate Gradle version"	
    shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"	
    register: gradle_ver	

  - fail:	
      msg: "Seems to be gradle {{ gradle_version }} is missing ... aborting"	
    when: gradle_ver.rc != 0	

  when: not gradle_present.stat.exists	

  - name: "Validate Gradle version"	
  shell: "{{ gradle_link }} -v | grep {{ gradle_version }}"	
  changed_when: False	
  register: gradle_ver	


- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: 'add users to docker group'
  user:
    name: 'ubuntu'
    groups: 'docker'
    append: 'yes'

- name: restart docker
  systemd:
    state: started
    name: docker