- name: clone repository project
  git:
    repo: https://github.com/CrisMon-01/UbuntuAnsibleGradleDocker
    dest: /home/ubuntu/project

#- name: Execute gradle build
#  shell: sudo ./gradle wrapper
#  args:
#    chdir: project/

#- name: Execute gradle build
#  shell: sudo gradle build
#  args:
#    chdir: project/

- debug:
    msg: "Gradle {{ gradle_version }} is installed"
  when: gradle_ver.rc == 0