- name: clone repository project
  git:
    repo: https://github.com/CrisMon-01/UbuntuAnsibleGradleDocker
    dest: /home/ubuntu/project

- name: Execute gradle build
  shell: gradle build
  args:
    chdir: project/

- debug:
    msg: "Gradle {{ gradle_version }} is installed"
  when: gradle_ver.rc == 0

